package io.github.lightrag.api;

public enum FailureStage {
    SNAPSHOT_LOADING,
    SNAPSHOT_RECOVERY,
    GRAPH_INSPECTION,
    ENTITY_MATERIALIZATION,
    RELATION_MATERIALIZATION,
    VECTOR_REPAIR,
    FINALIZING
}
