package io.github.lightrag.api;

public enum TaskType {
    INGEST_DOCUMENTS,
    INGEST_SOURCES,
    DELETE_DOCUMENT,
    REBUILD_GRAPH,
    RESUME_DOCUMENT_INGEST,
    MATERIALIZE_DOCUMENT_GRAPH,
    MATERIALIZE_CHUNK_GRAPH
}
