package io.github.lightrag.api;

public enum TaskEventType {
    TASK_SUBMITTED,
    TASK_RUNNING,
    TASK_SUCCEEDED,
    TASK_FAILED,
    TASK_CANCELLED,
    TASK_METADATA_UPDATED,
    STAGE_STARTED,
    STAGE_SUCCEEDED,
    STAGE_SKIPPED,
    STAGE_FAILED,
    DOCUMENT_STARTED,
    DOCUMENT_CHUNKED,
    DOCUMENT_GRAPH_READY,
    DOCUMENT_VECTORS_READY,
    DOCUMENT_COMMITTED,
    DOCUMENT_FAILED,
    DIAGNOSTIC_TIMING,
    LISTENER_FAILED
}
